### ISSUE TITLE
Cluster-autoscaler runaway scale-up and daemonsets

### ISSUE THREAD

**Issue by SQUIDwarrior** [uswitch/nidhogg#23]
How do you make this work with the cluster-autoscaler so it will not just keep spinning up nodes in the event of a daemonset failure? For example, if we set taints based on daemonsets A and B, and then there's an issue where daemonset B is broken and crashlooping, the autoscaler will just keep spinning up tainted nodes because it sees that there are pending pods. Is there a way to prevent this from happening?

**Comment by Joseph-Irving** [comment]
In most cases you would probably want this behaviour. 
e.g: you try to schedule a new pod, autoscaler creates new node, that node fails for some strange reason, it's critical daemonsets aren't working, no pods are scheduled on it, autoscaler creates another new node, it come up successfully, yay.
The scenario you're describing where the critical Daemonsets are broken cluster wide, would indicate you're having a some kind of serious cluster problem, in which case you would probably want someone to manually intervene, turn off autoscaler and fix whatever is broken with your cluster.

**Comment by SQUIDwarrior** [comment]
I actually found the latest version of the autoscaler has a `--ignore-taint` flag that does exactly this. But you do have a good point. We will see how this works in our cluster. I'm closing this issue because I figured out what I need, and I don't think it's the responsibility of Nidhogg to handle this case anyway.
